### ISSUE TITLE
Implement Jazzband guidelines for project django-simple-menu

### ISSUE THREAD

**Issue by jazzband-bot** [jazzband/django-simple-menu#62]
This issue tracks the implementation of the [Jazzband guidelines](https://jazzband.co/about/guidelines) for the project [django-simple-menu](https://github.com/jazzband/django-simple-menu)

It was initiated by @borgstrom who was automatically assigned in addition to the [Jazzband roadies](https://jazzband.co/roadies).

See the [TODO list](#todos) below for the generally required tasks, but feel free to update it in case the project requires it.

Feel free to ping a [Jazzband roadie](https://jazzband.co/roadies) if you have any question.

## TODOs<a name="todos"></a>

- [x] Fix all links in the docs (and README file etc) from old to new repo
- [x] Add the [Jazzband badge](https://jazzband.co/about/guidelines#badges) to the `README` file
- [x] Add the [Jazzband contributing guideline](https://jazzband.co/about/guidelines#contributing-guidelines) to the `CONTRIBUTING.md` file
- [x] Check if continuous testing works (e.g. [Travis-CI](https://travis-ci.org/), [CircleCI](https://circleci.com), [AppVeyor](https://www.appveyor.com), etc)
- [x] Check if test coverage services work (e.g. [Coveralls](https://coveralls.io), [Codecov](https://codecov.io), etc)
- [x] Add `jazzband` account to [PyPI](https://pypi.python.org/) project as maintainer role (URL: `https://pypi.python.org/pypi?:action=role_form&package_name=<PROJECTNAME>`)
- [x] Add `jazzband-bot` as maintainer to the [Read the Docs](https://readthedocs.org/) project (URL: `https://readthedocs.org/dashboard/<PROJECTNAME>/users/`)
- [x] Fix project URL in [GitHub project](https://github.com/jazzband/django-simple-menu) description
- [x] Review project if other services are used and port them to Jazzband

## Project details

<table>
  <caption></caption>
  <tr>
    <td>Description</td>
    <td>Simple, yet powerful, code-based menus for Django applications</td>
  </tr>
  <tr>
    <td>Homepage</td>
    <td>None</td>
  </tr>
  <tr>
    <td>Stargazers</td>
    <td>65</td>
  </tr>
  <tr>
    <td>Open issues</td>
    <td>8</td>
  </tr>
  <tr>
    <td>Forks</td>
    <td>39</td>
  </tr>
  <tr>
    <td>Default branch</td>
    <td>master</td>
  </tr>
  <tr>
    <td>Is a fork</td>
    <td>False</td>
  </tr>
  <tr>
    <td>Has Wiki</td>
    <td>False</td>
  </tr>
  <tr>
    <td>Has Pages</td>
    <td>False</td>
  </tr>
</table>

**Comment by jezdez** [comment]
Hey @mbeijen, Jazzband founder and roadie here, I've seen you having made some changes recently, would you'd like to become project lead for this project? The idea is that you'd be able to cut releases to PyPI that way.

**Comment by mbeijen** [comment]
I'm honored ☺️. I see that the project could use a steward and I would be available to pick this up.

**Comment by jezdez** [comment]
> I'm honored ☺️. I see that the project could use a steward and I would be available to pick this up.

Excellent!

@borgstrom Would you be okay with that? I could add you both as project leads. I know this is an old ticket, I'm sorry 😬

**Comment by borgstrom** [comment]
@jezdez @mbeijen - Sounds good to me 👍

**Comment by jezdez** [comment]
> @jezdez @mbeijen - Sounds good to me 👍

Thank you both, I've added you to the project, https://jazzband.co/projects/django-simple-menu.

Please be so kind and read both the [Jazzband guidelines](https://jazzband.co/about/guidelines) and the [release documentation](https://jazzband.co/about/releases) (slightly outdated as it's still mentioning Travis CI, but the same applies to the new GitHub Actions based CI).

I'm closing this now as done!
